// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRPDiw3vabNqhnB__q4yZRkOfworDMoy0',
    appId: '1:270162620721:web:66bd214dd4faa6a2284010',
    messagingSenderId: '270162620721',
    projectId: 'shawka-689fa',
    authDomain: 'shawka-689fa.firebaseapp.com',
    storageBucket: 'shawka-689fa.firebasestorage.app',
    measurementId: 'G-W0MVJ8VLV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWXJDlvPZAgYxuegEvgrqYLLQLCYpady8',
    appId: '1:270162620721:android:02ac5348cc993138284010',
    messagingSenderId: '270162620721',
    projectId: 'shawka-689fa',
    storageBucket: 'shawka-689fa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_iPUO9IPUsziw-rf6aQk_fOweO0W2M98',
    appId: '1:270162620721:ios:5ab461096b00d23c284010',
    messagingSenderId: '270162620721',
    projectId: 'shawka-689fa',
    storageBucket: 'shawka-689fa.firebasestorage.app',
    iosBundleId: 'com.xyronix.shawka',
  );
}
